# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :CI do
    # add actions here: https://docs.fastlane.tools/actions
	run_tests(
  	workspace: "MGPicsque.xcworkspace",
  	scheme: "MGPicsqueTests",
  	clean: true
	)
  end
  lane :CD do |values|
 
    gym(scheme: 'MGPicsque', project: "MGPicsque.xcodeproj", clean: true, silent: true, include_bitcode: false, export_method: 'ad-hoc')
 
    crashlytics(
    api_token: "93709ebde8fa6d3637931fb32b40b91cd4cf1e98",
    build_secret: "8085ae2f681f362bcc20370e0299db002d1efa1239bd3c23483b32e205efc12f"
  )
 
    end
end

