# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :CI do
    # add actions here: https://docs.fastlane.tools/actions
	run_tests(
  	workspace: "MGPicsque.xcworkspace",
  	scheme: "MGPicsqueTests",
  	clean: true
	)
  end
  lane :CD do |values|
 
    gym(scheme: 'MGPicsque', project: "MGPicsque.xcodeproj", clean: true, silent: true, include_bitcode: false, export_method: 'ad-hoc')
 
    emails = values[:test_email] ? values[:test_email] : ['[email]'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here
 
    crashlytics(api_token: '[CRASHLYTICS_API_TOKEN]',
             build_secret: '[CRASHLYTICS_ORG_SECRET]',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?
 
    end
end
